### ISSUE TITLE
Respect CC, CXX, etc. from environment if provided

### ISSUE THREAD

**Issue by jakirkham** [lucastheis/cmt#10]
Currently the compilers and flags are pre-determined by `setup.py`. However, if environment variables are set to pick a particular compiler or add some different flags, these are not respected. In particular, if the user selects a compiler different from the system (a personal gcc compiler with OpenMP on Mac OS X or a new enough version of clang with OpenMP support), it has no effect. It would be nice if the standard environment variables were respected in these cases.

**Comment by lucastheis** [comment]
The environment variables will now only be set if they are not already set (1bbbb9).

**Comment by jakirkham** [comment]
Awesome. Thanks for that change.

We have a custom `gcc` built on Mac so we can build things like this with OpenMP support and C++11 support. So, this will definitely help with that.
