### ISSUE TITLE
Using an external copy of Eigen

### ISSUE THREAD

**Issue by jakirkham** [lucastheis/cmt#11]
If I have a copy of Eigen on my system, is there some way for me to tell cmt to use that copy of Eigen instead of the one included with the source code here?

**Comment by FlorianFranzen** [comment]
Eigen is a header only library, so which Eigen you use only matters at build time.

If you want to use your own Eigen, just delete the ```code/Eigen``` folder and either symlink your preferred version of Eigen in its place or change ```setup.py``` to have your version of Eigen in the include paths.
