### ISSUE TITLE
CMake build for lbfgs

### ISSUE THREAD

**Issue by jakirkham** [lucastheis/cmt#21]
The lbfgs library seems to build with `make` on UNIX or a Visual Studio project file on Windows. It would be nice if it built using CMake, which would allow it to build nicely on all platforms. Also, this would avoid needing particular version of the Visual Studio files to get it to build with a particular version of Visual Studio.

**Comment by FlorianFranzen** [comment]
[liblbfgs](http://www.chokkan.org/software/liblbfgs/) is not maintained by us but by its original author [here on github](https://github.com/chokkan/liblbfgs). Please report any issues there.
