### ISSUE TITLE
Matlab Interface Installation

### ISSUE THREAD

**Issue by maragkgm** [lucastheis/cmt#33]
Dear Lucas, 

May I ask something please? 

I'm trying to install the Conditional Modeling Toolkit, and in its Readme file it says that "normally it should be enough to download one of the prebuild binaries of our cmt matlab interface". 

Could you please explain how I can download one of the prebuild binaries of the cmt matlab interface?

Thank you for your time, 

George

**Comment by lucastheis** [comment]
Hi George,

Unfortunately, it looks like the prebuilt mex files are no longer available. My apologies.
