### ISSUE TITLE
windows installation

### ISSUE THREAD

**Issue by ABexter** [lucastheis/cmt#6]
Hello,
I'm struggling with installing the module on my windows 64-bit machine (Python 2.7), I'm not able to build it. Is there any precompiled version available? Or do you have some tips for me, maybe?
Thanks!

**Comment by lucastheis** [comment]
Unfortunately I cannot help you with Windows since I don't use it. I think @FloFra got it to work on Windows.

An easier way to use this code is probably via Docker: https://docs.docker.com/windows/

**Comment by NoamGit** [comment]
@FloFra - If so, can you please elaborate how to install it on windows?
