### ISSUE TITLE
Installing matlab version of c2s

### ISSUE THREAD

**Issue by HoltmaatLab** [lucastheis/cmt#7]
Hi all,
thanks for this analysis program.
Could you tell us how to install the Matlab version on Linux ??
( I successfully installed it in Python but I am more used to use Matlab) ....

Thanks

**Comment by lucastheis** [comment]
Did you try the instructions in the readme file, https://github.com/lucastheis/cmt#matlab-interface-installation?

**Comment by HoltmaatLab** [comment]
Actually, cmt is well installed. What I can't find is the c2s.m ....
Thanks

**Comment by FloFra** [comment]
@HoltmaatLab: Are you sure the c2s.m error comes from running any of the code that comes with cmt? We do not use a function with that name in our implementation. A quick round of googling seems to suggest that it is part of the "Statistical Pattern Recognition Toolbox" with which we are not affiliated.

**Comment by lucastheis** [comment]
I missed the "c2s" bit (https://github.com/lucastheis/c2s). While cmt has a Matlab interface, there is unfortunately no Matlab version of c2s (yet). Sorry @HoltmaatLab.
