### ISSUE TITLE
Using a BLAS other than MKL

### ISSUE THREAD

**Issue by jakirkham** [lucastheis/cmt#9]
What is MKL being used for here? Is it simply for the BLAS? If so, would it be possible to use another BLAS like ATLAS or OpenBLAS?

**Comment by lucastheis** [comment]
Any BLAS implementation should work. OpenBLAS should be as fast as MKL now (or always was and I just wasn't aware of it) and is much easier to install, so I will remove the instructions to install MKL from the readme file.

**Comment by jakirkham** [comment]
Thanks for clarifying. Yeah, I'm pretty fond of OpenBLAS. It's ability to detect architecture at run time and select the right assembly optimized kernels is great. Plus the straightforward license just makes it simpler to reason about how it fits with other things.

How does BLAS selection work? Do I need to supply some particular flags (e.g. `CXXFLAGS`, `CFLAGS`, `LDFLAGS`) or some Python options in order to enable this?
